spring.application.name=MedSync

server.port=8080

# Database
spring.datasource.url=
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update



