spring.application.name=MedSync

server.port=8080

# Database
spring.datasource.url=jdbc:mysql://34.176.165.124/medsync
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update


# Auth0 Utils
jwt.secret=0WTpTaYWqxBHZz3jRL0BeB4guTBZo32g7gi/NYiT18E=
auth0.domain=dev-g434k75n4xkqktvu.us.auth0.com
auth0.issuer=https://${auth0.domain}/
auth0.clientId=dFiumfdUMSZIHLR1YSG1I1Ke1OoDZ1RG
auth0.clientSecret=tbgLiFNvbWGtAoPm7B-SNkYgcNcas6E22qHR_LdVRZHFCeXpqvsV1R4hQMi_yGiD
auth0.audience=https://medsync-auth/api

# Auth0 Config
spring.security.oauth2.client.registration.auth0.client-id=${auth0.clientId}
spring.security.oauth2.client.registration.auth0.client-secret=${auth0.clientSecret}
spring.security.oauth2.client.provider.auth0.issuer-uri=https://${auth0.domain}/
